bug where could not create game from teams when id != card number
seems prior migration issue which I discovered switching to postgres and
running a migration:

django.db.utils.ProgrammingError: multiple primary keys for table "scorerSheet_team" are not allowed

hence I deleted all migration files and created one new one based on
current models.py

also changed max_num=4 to max_num=3 because the empty player row in
create_line threw a validation error, we probably need to calculate this
value based on number of players in team